#!/usr/bin/env bash
# This script create a file that generate its PID
# Also return a message after error encounter
# Finally terminate at final call of deleting script

rmfile_n_exit()
{
    rm -f /var/run/myscript.pid;
    exit
}
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; rmfile_n_exit" SIGTERM
trap "echo 'I hate the kill command'; rmfile_n_exit" SIGQUIT


echo $$ >> /var/run/myscript.pid
while (true)
do
    echo 'To infinity and beyond'
    sleep 2
done
