#!/bin/bash

# Assign the variables for the server, key file, and user
server="8.8.8.8"
key_file="~/.ssh/school"
user="ubuntu"

# Connect to the server using ssh with the specified key file and user
ssh -i $key_file -o user=$user $server
